name: E2E Tests

on:
  deployment_status:

jobs:
  lighthouse:
    name: Run lighthouse
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          runs: 5
          urls: |
            ${{ github.event.deployment_status.environment_url }}
          budgetPath: ./budget.json
          configPath: ./lighthouserc.json

      - name: Display Lighthouse results
        uses: manrueda/lighthouse-report-action@master
        with:
          reports: .lighthouseci
          github-token: ${{ secrets.GITHUB_TOKEN }}
