name: E2E Tests

on:
  deployment_status:

jobs:
  lighthouse:
    name: Run lighthouse
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    permissions:
      contents: read
    env:
      DEPLOYMENT_URL: ${{ github.event.deployment_status.environment_url }}
    steps:
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ github.event.deployment_status.environment_url }}
          budgetPath: ./budget.json
