name: Local Tests

on:
  pull_request:

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Check
        run: pnpm next lint .

      - name: Format Check
        run: biome ci --reporter=github

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Next.js
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.*js', '**/*.*ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Check
        run: pnpm build
